services:
  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    container_name: ads-app
    volumes:
      - ./:/app
  webserver:
    image: "nginx:alpine"
    container_name: ads-webserver
    ports:
      - 80:80
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf